### ISSUE TITLE
[minor issue] shebang is missing

### ISSUE THREAD

**Issue by mb6ockatf** [IvanIsak2000/finance_manager_app#16]
```bash
$ . src/main.py
bash: $'\r': command not found
bash: import: command not found
bash: import: command not found
bash: import: command not found
bash: import: command not found
bash: from: command not found
bash: from: command not found
bash: import: command not found
bash: import: command not found
bash: $'\r': command not found
bash: $'\r': command not found
bash: src/main.py: line 13: syntax error near unexpected token `('
'ash: src/main.py: line 13: `def display_status(text):
```

**Comment by IvanIsak2000** [comment]
> ```shell
> $ . src/main.py
> bash: $'\r': command not found
> bash: import: command not found
> bash: import: command not found
> bash: import: command not found
> bash: import: command not found
> bash: from: command not found
> bash: from: command not found
> bash: import: command not found
> bash: import: command not found
> bash: $'\r': command not found
> bash: $'\r': command not found
> bash: src/main.py: line 13: syntax error near unexpected token `('
> 'ash: src/main.py: line 13: `def display_status(text):
> ```

Try to activate shell before `src` repo. After `cd src` and run main.py here
