### ISSUE TITLE
`matplotlib` drops an exception. Graph cannot be plotted

### ISSUE THREAD

**Issue by mb6ockatf** [IvanIsak2000/finance_manager_app#2]
```
UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
```

**Comment by mb6ockatf** [comment]
i'll fix it in the next pull request

**Comment by IvanIsak2000** [comment]
> ```
> UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
>   plt.show()
> ```

this is usually displayed when the database is empty;  I also noticed that if the database is not empty, this message is constantly displayed, but it does not interfere with the work 🤓

**Comment by IvanIsak2000** [comment]
Well, the program can clear the terminal with a message each time it is configured :)

**Comment by mb6ockatf** [comment]
> Well, the program can clear the terminal with a message each time it is configured :)

the thing is, as i wrote in the title - i could not make it plot anything (may be i was doing something wrong).
I don't care about messages it prints - it's not important at all

may be it fails to plot just on my computer (i have archlinux system). I think it's worth reopening this issue

**Comment by mb6ockatf** [comment]
@IvanIsak2000 i have checked it one more time. nothing is plotted after `read -> show schedule` button is clicked. Moreover, it freezes after i click it, so the app can only be terminated via terminal

Does it work normally on your computer?

**Comment by IvanIsak2000** [comment]
I have run everything on my win10 and it works fine
![image](https://user-images.githubusercontent.com/79650307/226645610-f97d2d55-e5c0-4a68-ad77-cf498e42756a.png)

**Comment by IvanIsak2000** [comment]
> @IvanIsak2000 i have checked it one more time. nothing is plotted after `read -> show schedule` button is clicked. Moreover, it freezes after i click it, so the app can only be terminated via terminal
> 
> Does it work normally on your computer?

@mb6ockatf 
Can you show what is displayed when the graph is shown?

**Comment by IvanIsak2000** [comment]
Ubuntu
![image](https://user-images.githubusercontent.com/79650307/226647717-5a77232e-ae16-4470-b54b-233ceb69fe70.png)

**Comment by mb6ockatf** [comment]
@IvanIsak2000 i've solved it. `matplotlib` depends on Tkinter, which was not installed. I'll add it to `requirements.txt` in my PR
